version: 0.2



phases:



  install:

    runtime-versions:

      java: corretto11



  pre_build:

    commands:

      - echo In the pre_build phase...



  build:

    commands:

      - echo Build started on `date`s



  post_build:
    commands:
    - echo Build completed on `date`
    - mvn clean
    - mvn package
    - mv target/Customer-Service-0.0.1-SNAPSHOT.jar Customer-Service-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - Customer-Service-0.0.1-SNAPSHOT.jar
  - .ebextensions/**/*